#!/usr/bin/env python3
"""Bake the fallback schedule blob into apps/catabus/app.py.

Reads CATA's google_transit.zip (a local path, or downloads the live one),
trims it to what the DEFAULT config needs — routes V/VE/NV, stop_times at
the default + fallback stops only, the full (small) stop list for held-bus
names — rebuilds a minimal GTFS zip, and writes it base64'd between the
SCHEDULE codegen markers in app.py. That blob is the app's last resort
when catabus.com is unreachable and no cache exists, so it only has to
cover the out-of-the-box Vairo config.

Also writes tests/data/gtfs_trimmed.zip so the test suite stays hermetic.

Usage:
    python tools/build_schedule.py [zip-path-or-url] [--write]

Without --write it prints what would change. Re-run each semester when
CATA publishes a new zip (the app itself prefers the live download; this
blob is belt-and-braces).
"""

import base64
import csv
import io
import re
import sys
import textwrap
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_PATH = ROOT / "apps" / "catabus" / "app.py"
FIXTURE_PATH = ROOT / "tests" / "data" / "gtfs_trimmed.zip"

GTFS_URL = "https://catabus.com/wp-content/uploads/google_transit.zip"
KEEP_ROUTES = {"V", "VE", "NV"}
KEEP_STOPS = {"504", "506", "503", "507"}

BEGIN = "# --- BEGIN GENERATED: SCHEDULE ---"
END = "# --- END GENERATED: SCHEDULE ---"


def load_zip(source):
    if source and not source.startswith(("http://", "https://")):
        return Path(source).read_bytes()
    url = source or GTFS_URL
    print(f"downloading {url}")
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read()


def trim(zip_bytes):
    zf = zipfile.ZipFile(io.BytesIO(zip_bytes))

    def rows(name):
        with zf.open(name) as f:
            return list(csv.DictReader(
                io.TextIOWrapper(f, "utf-8-sig", newline="")))

    routes = [r for r in rows("routes.txt")
              if (r.get("route_short_name") or "").upper() in KEEP_ROUTES]
    route_ids = {r["route_id"] for r in routes}
    trips = [t for t in rows("trips.txt") if t["route_id"] in route_ids]
    trip_ids = {t["trip_id"] for t in trips}
    service_ids = {t["service_id"] for t in trips}
    stop_times = [s for s in rows("stop_times.txt")
                  if s["trip_id"] in trip_ids and s["stop_id"] in KEEP_STOPS]
    cal_dates = [c for c in rows("calendar_dates.txt")
                 if c["service_id"] in service_ids]
    stops = rows("stops.txt")  # all of them — tiny, and held-bus
    #                            marquees can name any stop on the route
    agency = rows("agency.txt")

    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        def write(name, rowlist):
            if not rowlist:
                return
            buf = io.StringIO()
            w = csv.DictWriter(buf, fieldnames=list(rowlist[0].keys()))
            w.writeheader()
            w.writerows(rowlist)
            z.writestr(name, buf.getvalue())

        write("agency.txt", agency)
        write("routes.txt", routes)
        write("trips.txt", trips)
        write("stops.txt", stops)
        write("stop_times.txt", stop_times)
        write("calendar_dates.txt", cal_dates)
    print(f"trimmed: {len(routes)} routes, {len(trips)} trips, "
          f"{len(stop_times)} stop_times rows, {len(cal_dates)} "
          f"calendar dates -> {len(out.getvalue())} bytes zipped")
    return out.getvalue()


def bake(blob, write):
    b64 = base64.b64encode(blob).decode()
    lines = textwrap.wrap(b64, 72)
    literal = "SCHEDULE_FALLBACK_B64 = (\n" + "\n".join(
        f'    "{ln}"' for ln in lines) + "\n)"
    block = (f"{BEGIN}\n"
             "# generated by tools/build_schedule.py — do not edit by "
             "hand. A trimmed\n"
             "# GTFS zip (routes V/VE/NV at the default + fallback stops "
             "only) used when\n"
             "# the live google_transit.zip can't be downloaded and no "
             "cache exists.\n"
             f"{literal}\n"
             f"{END}")
    src = APP_PATH.read_text()
    new_src, n = re.subn(
        re.escape(BEGIN) + ".*?" + re.escape(END), lambda _m: block,
        src, flags=re.S)
    if n != 1:
        sys.exit(f"expected exactly one SCHEDULE block in {APP_PATH}, "
                 f"found {n}")
    if not write:
        changed = "would change" if new_src != src else "unchanged"
        print(f"{APP_PATH}: {changed} ({len(b64)} chars of base64); "
              "re-run with --write")
        return
    APP_PATH.write_text(new_src)
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_bytes(blob)
    print(f"wrote {APP_PATH} ({len(b64)} chars of base64) and "
          f"{FIXTURE_PATH}")


def main():
    args = [a for a in sys.argv[1:] if a != "--write"]
    write = "--write" in sys.argv[1:]
    blob = trim(load_zip(args[0] if args else None))
    bake(blob, write)


if __name__ == "__main__":
    main()
